version: "3.9"
volumes:
  postgres_data:
  web:
services:
  postgis:
    image: kartoza/postgis:latest
    volumes:
      - postgis-data=/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12b34c56a78k
      - ALLOW_IP_RANGE=0.0.0.0/0
    expose:
      - "5432"
    healthcheck:
      test: "PGPASSWORD=12b34c56a78k pg_isready -h remember_places_postgis_1 -U postgres -d postgres"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 172.18.0.4:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - migrations
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py migrate --no-input
    environment:
      DATABASE_URL: postgres://postgres:12b34c56a78k@remember_places_postgis_1:5432/postgres
    volumes:
      - .:/code
    depends_on:
      postgis:
        condition: service_healthy
